version: "3.0"

services:   
  app:
    build: .
    container_name: app
    depends_on: 
      - neo4j
    volumes:
      - .:/app
    env_file:
      - .env

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
