version: "3.0"

services:   
  neo4j:
    image: neo4j:5.7.0-community
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/$AUTH_PASS
  app:
    build: .
    container_name: cli_app
    links: 
      - neo4j
    volumes:
      - .:/app
    env_file:
      - .env
    

volumes:
  neo4j_data:
